# Page settings

baseURL = "https://pixelchrome.org/about/"
languageCode = "en"
title = "Harald Dumdey about"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-40306725-2"

[params]
    author = "Harald Dumdey"
    description = "Harald Dumdey Resume/CV"

    primaryColor = "#2E74B5"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Harald Dumdey"
        tagline = "Solutions Engineer"
        avatar = "welcome_avatar.png"

    [params.contact]
        enable = true
        location = "Möhrendorf"

        [[params.contact.list]]
        icon = "fas fa-phone"
        url = "tel:#"
        text = "+49 9131 5313909"
        [[params.contact.list]]
        icon = "fas fa-envelope"
        url = "mailto:contact@pixelchrome.org"
        text = "contact@pixelchrome.org"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://pixelchrome.org/cv"
        text = "pixelchrome.org/cv"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "SAN / NAS / Object Storage"
        [[params.skills.list.items]]
        details = "vSphere / HyperV / Openstack"
        [[params.skills.list.items]]
        details = "Solaris / FreeBSD / Linux"
        [[params.skills.list.items]]
        details = "Ansible"
        [[params.skills.list.items]]
        details = "K8S / Docker"
        [[params.skills.list.items]]
        details = "MySQL / MongoDB / Oracle"
        [[params.skills.list.items]]
        details = "AWS / Google / Azure"
        [[params.skills.list.items]]
        details = "Postfix / Dovecot / RSpamd"
        [[params.skills.list.items]]
        details = "Apache / NGINX"
        [[params.skills.list.items]]
        details = "Shell / HTML / CSS / Python"
        [[params.skills.list.items]]
        details = "Git / Jenkins"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Pre- and Post-Sales"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Escalation handling"

    [params.member]
        enable = true

        [[params.member.list]]
        title = "Specialist Groups"
        [[params.member.list.items]]
        details = "DevOps"
        [[params.member.list.items]]
        details = "Cloud Data Services"
        [[params.member.list.items]]
        details = "Security"    

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "State-certified engineer (data processing)"
        university = "Technical College Erlangen"
        dates = "1996 - 1998"

        [[params.education.list]]
        degree = "Electronic technician trainee"
        university = "Siemens Erlangen"
        dates = "1987 - 1991"

    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "German"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Running"
        [[params.interests.list]]
        name = "Skiing"
        [[params.interests.list]]
        name = "Photography"

    [params.summary]
        enable = true
        text = "Computer nerd since 1984. IT-Professional since 1997. Creative and positive thinker with 'a different view', Teamplayer & Autodidact."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Cloud & Software Solution Architect "
        dates = "2021 - Present"
        company = "NetApp"
        details = "I work with sales specialists and management to create and execute on a strategy for success of NetApps SaaS business in the DACH (Germany, Austria & Switzerland) region. It is my responsibility to understand customer problems and initiatives, architect appropriate solutions, design and run proof-of-concepts and onboard customers into active consumption. My focus is on products for hybrid cloud monitoring, optimization, troubleshooting and protecting data from ransomware and potential misuse."

        [[params.experience.list]]
        title = "Solutions Engineer"
        dates = "2016 - 2021"
        company = "NetApp"
        details = "In my role as Solutions Engineer, I was responsible for 'Enterprise Accounts' in Germany. I provided technical knowledge and support to customers with on-site and remote meetings, workshops and POCs. With a strong technical background, I evaluated customer requirements and developed on-premise, hybrid and multi-cloud solutions to meet customer needs."
        [[params.experience.list.items]]
        details = "German based multinational sports clothing and shoe vendor."
        [[params.experience.list.items]]
        details = "Service provider for tax, accountant and attorneys."
        [[params.experience.list.items]]
        details = "Several automotive vendors."
        [[params.experience.list.items]]
        details = "Named and hunting accounts until 2018"

        [[params.experience.list]]
        title = "Global Systems Engineer"
        dates = "2013 - 2018"
        company = "NetApp"
        details = "Presales role for 'Global Accounts' with a similar function to my current role. Dedicated for the largest Europe-based electronics and electrical engineering company headquartered in Munich and Berlin."

        [[params.experience.list]]
        title = "Global Systems Engineer"
        dates = "2010 - 2013"
        company = "NetApp"
        details = "Presales role for 'Services Provider' with a similar function to my current role. Dedicated for one of the biggest European Service Providers."

        [[params.experience.list]]
        title = "Technical Global Advisor"
        dates = "2007 - 2010"
        company = "NetApp"
        details = "Proactive & reactive support, single point of contact and coordination of escalations. Dedicated for one of the biggest European Service Provider."

        [[params.experience.list]]
        title = "Strategic Support Engineer & Proactive Technical Analyst"
        dates = "1999 - 2007"
        company = "Sun Microsystems"
        details = "Complex on-site installations, integration and migrations of high-end server and (SAN) storage systems had been a part of my job. I also did proactive analysis and recommendations for customers Datacenter environments."
        [[params.experience.list.items]]
        details = "Outsourcing- and Telecommunication Providers"
        [[params.experience.list.items]]
        details = "Financial industry"
        [[params.experience.list.items]]
        details = "Biggest market research institute in Germany"
        
        [[params.experience.list]]
        title = "System Support Engineer"
        dates = "1998 - 1999"
        company = "Silicon Graphics"
        details = "On-site installations, post-sales and technical support for high-end visualization systems and supercomputers (SGI Onyx and Origin)."

        [[params.experience.list]]
        title = "Laboratory Technician"
        dates = "1991 - 1998"
        company = "Siemens"
        details = "Electromagnetic Compatibility (EMC) testing labs & Laboratory for environmental testing."

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "New NetApp Customer (2020)"
        meta = "POC"
        tagline = "All Flash Metrocluster for most critical Database of multibillion dollar company"

        [[params.projects.list]]
        title = "New NetApp Customer (2018)"
        meta = "POC"
        tagline = "All-Flash + tiering to Object Storage + Backup SDS (Media)"

        [[params.projects.list]]
        title = "New NetApp Customer - Service Provider (2017)"
        meta = "POC"
        tagline = "Datastore for VMware vSphere based on SolidFire "

        [[params.projects.list]]
        title = "Multi Petabyte (2017)"
        meta = "RFP"
        tagline = "Medical solutions company"

        [[params.projects.list]]
        title = "Large scale All-Flash Storage incl. Backup + DR (2016)"
        meta = "Storage Design"

        [[params.projects.list]]
        title = "Transition Several 7toC projects (2015)"
        meta = "Tech Refresh"
        tagline = "Several 7toC projects - multi petabyte (7Mode ONTAP to clustered ONTAP)"

        [[params.projects.list]]
        title = "Siemens PLM Teamcenter (2015)"
        meta = "Migration"
        tagline = "One of the largest installations worldwide, Metrocluster, 15000 User"

    [params.certifications]
        enable = true

        [[params.certifications.list]]
        title = "SUSE Certified Administrator"
        details = "[SCA Rancher 2.5](assets/pdf/202108_SUSE_SCA_RAN2_570.pdf)"
        meta = "SUSE"
        [[params.certifications.list]]
        title = "Certified Rancher Operator"
        details = "[CRO K101](assets/pdf/202102_RANCHER_Certified_Rancher_Operator.pdf)"
        meta = "Rancher"
        [[params.certifications.list]]
        title = "NetApp Solutions Engineer Specialist"
        details = "[NSES DevOps - Pilot](assets/pdf/201904_NTAP_NSES_DevOps.pdf)"
        meta = "NetApp"
        [[params.certifications.list]]
        title = "NetApp Systems Engineer Professional" 
        meta = "NetApp"
        [[params.certifications.list.items]]
        details = "[NSEP Cloud](assets/pdf/201701_NTAP_Certificate_NSEP_Cloud.pdf)"
        [[params.certifications.list.items]]
        details = "[NSEP Data Protection](assets/pdf/201702_NTAP_Certificate_NSEP_Data_Protection.pdf)"
        [[params.certifications.list.items]]
        details = "[NSEP E-Series](assets/pdf/201701_NTAP_Certificate_NSEP_E­Series.pdf)"
        [[params.certifications.list.items]]
        details = "[NSEP ONTAP](assets/pdf/201702_NTAP_Certificate_NSEP_ONTAP.pdf)"
        [[params.certifications.list]]
        title = "SolidFire Cloud Builder Systems Engineer"
        details = "[CBSE Part 1](assets/pdf/201604_NTAP_Certificate_CBSE.pdf) & [Part 2](assets/pdf/201604_NTAP_Certificate_CBSE2.pdf)"
        meta = "SolidFire"
        [[params.certifications.list]]
        title = "SolidFire Cloud Builder Sales Associate"
        details = "[CBSA](assets/pdf/201604_NTAP_Certificate_CBSA.pdf)"
        meta = "SolidFire"
        [[params.certifications.list]]
        title = "NetApp Certified Clustered Data ONTAP Administrator"
        details = "NCDA NS0-156"
        meta = "NetApp"
        [[params.certifications.list]]
        title = "Sun certified systems installer for SunCluster"
        meta = "Sun Microsystems"

    [params.information]
        enable = false
        
        [[params.information.list]]
        title = "More Information"
        [[params.information.list.items]]
        details = "more information details"

    [params.highlights]
        enable = true

        [[params.highlights.list]]
        title = "Technologie Forum Bayern"
        tagline = "Speaker - DevOps (Fall 2019), Ansible (Spring 2019), DevOps & Container (2017)"
        meta = "NetApp"
        [[params.highlights.list]]
        title = "AWS Summit Berlin"
        tagline = "Speaker - Storage for the Cloud (2018)"
        meta = "AWS"
        [[params.highlights.list]]
        title = "NetApp Insight Berlin"
        tagline = "Speaker - Storage for the Cloud (2016)"
        meta = "NetApp"

    [params.trainings]
        enable = true
        
        [[params.trainings.list]]
        title = "[Certified Rancher Operator: Level One](assets/pdf/202102_RANCHER_Certified_Rancher_Operator.pdf)"
        meta = "Rancher"
        [[params.trainings.list]]
        title = "[The Complete Kubernetes Course](assets/pdf/201911_Udemy_The_Complete_Kubernetes_Course.pdf)"
        meta = "Udemy"
        [[params.trainings.list]]
        title = "[Advanced Kubernetes Usage](assets/pdf/201911_Udemy_Advanced_Kubernetes_Usage.pdf)"
        meta = "Udemy"
        [[params.trainings.list]]
        title = "[Google Cloud Certified Associate Cloud Engineer](assets/pdf/201909_LA_Google_Cloud_Certified_Associate_Cloud_Engineer.pdf)"
        meta = "Linux Academy"
        [[params.trainings.list]]
        title = "[Kubernetes the hard way](assets/pdf/201902_LA_Kubernetes_the_hard_way.pdf)"
        meta = "Linux Academy"
        [[params.trainings.list]]
        title = "[MongoDB for Developers M101P](assets/pdf/201802_MongoDB_for_Developers_M101P.pdf)"
        meta = "MongoDB"
        [[params.trainings.list]]
        title = "[MongoDB Basics M001](assets/pdf/201711_MongoDB_Basics_M001.pdf)"
        meta = "MongoDB"
        [[params.trainings.list]]
        title = "plus more than 200 internal and external trainings"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github"
        url = "https://github.com/pixelchrome"
        title = "pixelchrome"
        [[params.social.list]]
        icon = "fab fa-docker"
        url = "https://hub.docker.com/u/pixelchrome"
        title = "pixelchrome"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://linkedin.com/in/hdumdey"
        title = "hdumdey"
        [[params.social.list]]
        icon = "fab fa-mastodon"
        url = "https://mastodon.social/@pixelchrome"
        title = "@pixelchrome@mastodon.social"
        [[params.social.list]]
        icon = "fas fa-rss"
        url = "https://pixelchrome.org/blog"
        title = "pixelchrome.org/blog"
        [[params.social.list]]
        icon = "fas fa-camera"
        url = "https://pixelchrome.org"
        title = "pixelchrome.org"

[params.footer]
        copyright = "Harald Dumdey"
